### ISSUE TITLE
Bhrao

### ISSUE THREAD

**Issue by Bhrao123** [viperadnan-git/video-encoder-bot#18]
I created encode bot & Tested But it is Showing "[Errno 2] No such file or directory: 'ffprobe' " like this. What can I Do

**Comment by zYxDevs** [comment]
if u deploy on heroku, add this on buildpack and redeploy.
`https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest`

**Comment by zYxDevs** [comment]
if you deploy on other platform, do see this:
https://stackoverflow.com/questions/36092824/rails-ffmpeg-heroku-errnoenoent-no-such-file-or-directory-the-ffprobe

**Comment by Attacker336699** [comment]
> I created encode bot & Tested But it is Showing "[Errno 2] No such file or directory: 'ffprobe' " like this. What can I Do

Yes...same Problem to me too

**Comment by Attacker336699** [comment]
> if u deploy on heroku, add this on buildpack and redeploy. `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest`

Did i have to add this link to buildpack?

**Comment by andta200** [comment]
Hi,

1) Command ffmpeg line:
Run any video ffmpeg process

2) Compressed video: add caption

3) Bot button features: resolution, crf, preset, audio bitrate options

**Comment by viperadnan-git** [comment]
> > if u deploy on heroku, add this on buildpack and redeploy. `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest`
> 
> Did i have to add this link to buildpack?

Yes and after that deploy again, Heroku is not preferred you can encode only small videos on it.
